apiVersion: v1
kind: Pod
metadata:
  name: gpu-demo
spec:
  restartPolicy: OnFailure
  containers:
    - name: gpu-demo
      image: aneasystone/gpu-demo:v1
      resources:
        limits:
          nvidia.com/gpu: 1
